Repository colopl/laravel-spanner, pull requests merged in 2023-05, with the labels that each got.

#97 feature: add Schema\Grammar::typeDouble for better compatibility
  CHANGELOG.md
  src/Schema/Grammar.php
  tests/Schema/BlueprintTest.php
Labels: enhancement

#93 fix: FilesystemAdapter could not make 0777 directories
  CHANGELOG.md
  src/FileCacheAdapter.php
  src/SpannerServiceProvider.php
  tests/ConnectionTest.php
  tests/TestCase.php
Labels: bug

#99 feature: remove Connection's waitForOperation and isDoneOperation
  CHANGELOG.md
  src/Concerns/ManagesDataDefinitions.php
  src/Concerns/ManagesLongRunningOperations.php
  src/Connection.php
Labels: enhancement

#98 feature: deprecate runDdl and runDdls
  CHANGELOG.md
  composer.json
  src/Concerns/ManagesDataDefinitions.php
Labels: enhancement

#104 Update `export-ignore` entries in `.gitattributes`
  .gitattributes
  CHANGELOG.md
Labels: chore

#107 fix: Transaction state was not being cleared if rolled back failed
  CHANGELOG.md
  src/Concerns/ManagesTransactions.php
  tests/ConnectionTest.php
Labels: bug

#108 chore: fix phpstan errors
  phpstan.neon
Labels: chore
