Repository colopl/laravel-spanner, pull requests merged in 2023-04, with the labels that each got.

#86 fix: `Connection::statement` with DDLs was not logging and was not triggering events
  .gitignore
  CHANGELOG.md
  phpstan.neon
  src/Concerns/ManagesDataDefinitions.php
  src/Connection.php
  tests/Concerns/ManagesDataDefinitionsTest.php
  tests/ConnectionTest.php
  tests/Schema/BuilderTest.php
Labels: bug, enhancement

#88 fix: emulator support for Connection::listSessions
  CHANGELOG.md
  src/Concerns/ManagesSessionPool.php
  tests/ConnectionTest.php
  tests/Console/SessionsCommandTest.php
Labels: enhancement

#90 feature: use official CacheSessionPool from google/cloud-spanner
  CHANGELOG.md
  composer.json
  phpstan.neon
  src/Concerns/ManagesSessionPool.php
  src/Session/CacheSessionPool.php
  src/Session/DeleteOperation.php
  src/SpannerServiceProvider.php
  tests/Concerns/ManagesDataDefinitionsTest.php
  tests/ConnectionTest.php
  tests/SessionNotFoundTest.php
Labels: enhancement

#89 feature: separate connection per session so it is not shared
  CHANGELOG.md
  src/SpannerServiceProvider.php
  tests/ConnectionTest.php
  tests/Console/SessionsCommandTest.php
  tests/Console/WarmupCommandTest.php
Labels: enhancement

#87 fix: `Connection::createDatabase` was not logging and was not triggering events for given statements
  phpstan.neon
  src/Concerns/ManagesDataDefinitions.php
  tests/Concerns/ManagesDataDefinitionsTest.php
Labels: bug

#91 chore: use latest grpc (1.49 -> 1.54) for test
  Dockerfile
Labels: chore

#95 Fix incorrect and weak requirements
  README.md
  composer.json
Labels: question

#96 chore: update docker compose
  Makefile
  compose.yaml
Labels: chore
