Repository colopl/laravel-spanner, pull requests merged in 2025-01, with the labels that each got.

#246 Fix Grammar::substituteBindingsIntoRawSql fails during unnesting
  src/Connection.php
  tests/ConnectionTest.php
  tests/Query/UnnestTest.php
Labels: waiting for review

#247 chore: phpstan errors
  phpstan.neon
  src/Concerns/ManagesSessionPool.php
  src/Schema/Grammar.php
  tests/Console/CooldownCommandTest.php
Labels: chore

#248 feat: add php8.4 support
  Dockerfile
  composer.json
  src/Connection.php
  src/Schema/Builder.php
Labels: enhancement, waiting for review

#249 chore: symfony/deprecation-contracts is no longer used
  composer.json
Labels: chore, waiting for review

#250 chore: Connection:: __debugInfo cleanup
  src/Concerns/ManagesSessionPool.php
Labels: chore, waiting for review

#251 chore: add better phpdoc to TimestampBound
  src/TimestampBound/ExactStaleness.php
  src/TimestampBound/MaxStaleness.php
  src/TimestampBound/MinReadTimestamp.php
  src/TimestampBound/ReadTimestamp.php
  src/TimestampBound/StrongRead.php
  src/TimestampBound/TimestampBoundInterface.php
Labels: chore, waiting for review

#252 chore: remove unused option "useGapicBackoffs"
  src/SpannerServiceProvider.php
Labels: chore, waiting for review

#254 feat: deprecate Connection::getDoctrineConnection()
  src/Connection.php
Labels: enhancement, waiting for review

#253 chore: update laravel to 11.31 to avoid security vulnerability
  composer.json
Labels: chore, waiting for review

#255 feat: use expected type for Connection::__construct() to bypass phpstan errors
  phpstan.neon
  src/Connection.php
Labels: enhancement, waiting for review

#245 Support PHPStan 2.x
  composer.json
  phpstan.neon
  src/Concerns/ManagesMutations.php
  src/Concerns/ManagesPartitionedDml.php
  src/Concerns/ManagesTransactions.php
  src/Connection.php
  src/Eloquent/Concerns/DoesNotAutoIncrement.php
  src/Eloquent/Model.php
  src/Events/MutatingData.php
  src/Query/ArrayValue.php
  src/Query/Builder.php
  src/Query/Concerns/UsesMutations.php
  src/Query/Concerns/UsesPartitionedDml.php
  src/Query/Grammar.php
  src/Query/Parameterizer.php
  src/Query/Processor.php
  src/Schema/Blueprint.php
  src/Schema/Builder.php
  src/Schema/ChangeStreamDefinition.php
  src/Session/SessionInfo.php
  src/SpannerServiceProvider.php
Labels: enhancement, chore, waiting for review

#258 feat: support auto incrementing on Model
  phpstan.neon
  src/Eloquent/Concerns/DoesNotAutoIncrement.php
  src/Eloquent/Model.php
  src/Query/Grammar.php
  src/Query/Processor.php
  tests/Eloquent/ModelTest.php
  tests/Query/BuilderTest.php
  tests/test.ddl
Labels: enhancement, waiting for review

#260 feat: allow starting value to be set for generated columns
  src/Schema/ColumnDefinition.php
  src/Schema/Grammar.php
  tests/Schema/BlueprintTest.php
Labels: enhancement, waiting for review

#259 feat: rename table support
  src/Schema/Blueprint.php
  src/Schema/Grammar.php
  src/Schema/RenameDefinition.php
  tests/Schema/BlueprintTest.php
Labels: enhancement, waiting for review
